### PR TITLE
feat: Upgrade terraform-google-kubernetes-engine module to 29.0.0

### PR DESCRIPTION
**Pull request by mitch-hamm**
Update terraform-google-modules/kubernetes-engine to 29.0.0 which is the latest version without major breaking changes

### CODE REVIEW

**Review by ciiiii — COMMENTED** [review]
We may need to expose `deletion_protection`, it need to be configured before destroy.

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/b6f35606ab373d5f572ff873569aeee5e5bf7f32/variables.tf#L503-L507

**Comment by mitch-hamm** [comment]
> We may need to expose `deletion_protection`, it need to be configured before destroy.
> 
> https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/b6f35606ab373d5f572ff873569aeee5e5bf7f32/variables.tf#L503-L507

https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/blob/b6f35606ab373d5f572ff873569aeee5e5bf7f32/cluster.tf#L34
I believe it's exposed here so if we pass the var in it should override that

**Comment by maxsxu** [comment]
> Update terraform-google-modules/kubernetes-engine to 29.0.0 which is the latest version without major breaking changes

@mitch-hamm Could you verify if the breaking changes introduced in v30.x will affect us? if not we should be good to upgrade to latest version so we can benefit.

**Review by zerbitx — APPROVED** [review]

**Comment by mitch-hamm** [comment]
> > Update terraform-google-modules/kubernetes-engine to 29.0.0 which is the latest version without major breaking changes
> 
> @mitch-hamm Could you verify if the breaking changes introduced in v30.x will affect us? if not we should be good to upgrade to latest version so we can benefit.

Unfortunately they will affect us. It's some breaking changes with that version we can clear up in a follow PR though

**Pull request merged**
